#!/bin/bash
function list_empty {
    dir=$1
    tmp_file=.tmp
    ls -p $dir | grep -v ./ > $tmp_file
    file_count=`grep -c . $tmp_file`
    for ((i=1; i<=file_count; i++)); do
        file=`head -$i $tmp_file | tail -1`
        line_count=`grep -c . $dir/$file`
        if ((line_count == 0)); then
            echo $file
        fi
    done
    rm $tmp_file
}
#TESTCASE: list_empty ~/Desktop/new