#!/bin/bash
function factorial {
    num=$1
    if ((num == 0)); then
        fact=1
    else
        fact=$num
        for ((i=fact-1; i>=1; i--)); do
            fact=$((fact * i))
        done
    fi
    echo $fact
}
#TESTCASE: factorial 5
